language: go
go:
  - tip
before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
script:
  - go test -race -cover ./...
notifications:
  webhooks:
    urls:
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGtvc3R5YXJpbiUzQW1hdHJpeC5vcmcvJTIxRWNJT25NUXlUeUx3ZnRvVWxTJTNBbWF0cml4Lm9yZw"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never
